import { BiomeType } from '../types/world';
import { BlockId } from './blocks';

export interface BiomeConfig {
  readonly type: BiomeType;
  readonly name: string;
  readonly surfaceBlock: number;
  readonly subsurfaceBlock: number;
  readonly fillBlock: number;
  readonly treeType: 'oak' | 'birch' | 'spruce' | 'palm' | 'jungle' | 'cactus' | 'none';
  readonly foliageDensity: number;
  readonly temperatureRange: readonly [number, number];
  readonly humidityRange: readonly [number, number];
  readonly minHeight: number;
  readonly maxHeight: number;
  readonly colorTint: string;
}

export const BIOME_CONFIG: Readonly<Record<BiomeType, BiomeConfig>> = {
  [BiomeType.OCEAN]: {
    type: BiomeType.OCEAN,
    name: 'Ocean',
    surfaceBlock: BlockId.SAND,
    subsurfaceBlock: BlockId.SAND,
    fillBlock: BlockId.STONE,
    treeType: 'none',
    foliageDensity: 0,
    temperatureRange: [0.3, 0.7],
    humidityRange: [0.8, 1.0],
    minHeight: 20,
    maxHeight: 58,
    colorTint: '#1a5276',
  },
  [BiomeType.BEACH]: {
    type: BiomeType.BEACH,
    name: 'Beach',
    surfaceBlock: BlockId.SAND,
    subsurfaceBlock: BlockId.SAND,
    fillBlock: BlockId.STONE,
    treeType: 'palm',
    foliageDensity: 0.02,
    temperatureRange: [0.5, 0.9],
    humidityRange: [0.4, 0.7],
    minHeight: 58,
    maxHeight: 66,
    colorTint: '#f9e79f',
  },
  [BiomeType.PLAINS]: {
    type: BiomeType.PLAINS,
    name: 'Plains',
    surfaceBlock: BlockId.GRASS,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'oak',
    foliageDensity: 0.005,
    temperatureRange: [0.4, 0.8],
    humidityRange: [0.3, 0.6],
    minHeight: 62,
    maxHeight: 76,
    colorTint: '#7dcea0',
  },
  [BiomeType.FOREST]: {
    type: BiomeType.FOREST,
    name: 'Forest',
    surfaceBlock: BlockId.GRASS,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'oak',
    foliageDensity: 0.15,
    temperatureRange: [0.3, 0.7],
    humidityRange: [0.5, 0.8],
    minHeight: 64,
    maxHeight: 82,
    colorTint: '#196f3d',
  },
  [BiomeType.DESERT]: {
    type: BiomeType.DESERT,
    name: 'Desert',
    surfaceBlock: BlockId.SAND,
    subsurfaceBlock: BlockId.SAND,
    fillBlock: BlockId.STONE,
    treeType: 'cactus',
    foliageDensity: 0.01,
    temperatureRange: [0.8, 1.0],
    humidityRange: [0.0, 0.2],
    minHeight: 62,
    maxHeight: 74,
    colorTint: '#d4ac0d',
  },
  [BiomeType.MOUNTAINS]: {
    type: BiomeType.MOUNTAINS,
    name: 'Mountains',
    surfaceBlock: BlockId.STONE,
    subsurfaceBlock: BlockId.STONE,
    fillBlock: BlockId.STONE,
    treeType: 'spruce',
    foliageDensity: 0.03,
    temperatureRange: [0.1, 0.5],
    humidityRange: [0.2, 0.5],
    minHeight: 80,
    maxHeight: 200,
    colorTint: '#7f8c8d',
  },
  [BiomeType.SNOW]: {
    type: BiomeType.SNOW,
    name: 'Snow',
    surfaceBlock: BlockId.SNOW,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'spruce',
    foliageDensity: 0.04,
    temperatureRange: [0.0, 0.2],
    humidityRange: [0.3, 0.7],
    minHeight: 64,
    maxHeight: 90,
    colorTint: '#d5dbdb',
  },
  [BiomeType.SWAMP]: {
    type: BiomeType.SWAMP,
    name: 'Swamp',
    surfaceBlock: BlockId.GRASS,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'oak',
    foliageDensity: 0.08,
    temperatureRange: [0.5, 0.8],
    humidityRange: [0.7, 1.0],
    minHeight: 58,
    maxHeight: 68,
    colorTint: '#4a6741',
  },
  [BiomeType.JUNGLE]: {
    type: BiomeType.JUNGLE,
    name: 'Jungle',
    surfaceBlock: BlockId.GRASS,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'jungle',
    foliageDensity: 0.25,
    temperatureRange: [0.7, 1.0],
    humidityRange: [0.8, 1.0],
    minHeight: 62,
    maxHeight: 80,
    colorTint: '#1e8449',
  },
  [BiomeType.SAVANNA]: {
    type: BiomeType.SAVANNA,
    name: 'Savanna',
    surfaceBlock: BlockId.GRASS,
    subsurfaceBlock: BlockId.DIRT,
    fillBlock: BlockId.STONE,
    treeType: 'birch',
    foliageDensity: 0.02,
    temperatureRange: [0.7, 1.0],
    humidityRange: [0.1, 0.4],
    minHeight: 64,
    maxHeight: 78,
    colorTint: '#b7950b',
  },
} as const;
