import type { BlockType } from '../types/world';

export const BlockId = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  SAND: 4,
  WATER: 5,
  WOOD: 6,
  LEAVES: 7,
  SNOW: 8,
  GRAVEL: 9,
  COAL_ORE: 10,
  IRON_ORE: 11,
  GOLD_ORE: 12,
  DIAMOND_ORE: 13,
  OBSIDIAN: 14,
  LAVA: 15,
  CRYSTAL: 16,
  CACTUS: 17,
  MUSHROOM: 18,
  PLANKS: 19,
} as const;

export type BlockIdValue = (typeof BlockId)[keyof typeof BlockId];

export const BLOCK_DEFINITIONS: readonly BlockType[] = [
  {
    id: BlockId.AIR,
    name: 'Air',
    transparent: true,
    solid: false,
    textures: { top: 0, bottom: 0, sides: 0 },
    emissive: false,
  },
  {
    id: BlockId.GRASS,
    name: 'Grass',
    transparent: false,
    solid: true,
    textures: { top: 1, bottom: 3, sides: 2 },
    emissive: false,
  },
  {
    id: BlockId.DIRT,
    name: 'Dirt',
    transparent: false,
    solid: true,
    textures: { top: 3, bottom: 3, sides: 3 },
    emissive: false,
  },
  {
    id: BlockId.STONE,
    name: 'Stone',
    transparent: false,
    solid: true,
    textures: { top: 4, bottom: 4, sides: 4 },
    emissive: false,
  },
  {
    id: BlockId.SAND,
    name: 'Sand',
    transparent: false,
    solid: true,
    textures: { top: 5, bottom: 5, sides: 5 },
    emissive: false,
  },
  {
    id: BlockId.WATER,
    name: 'Water',
    transparent: true,
    solid: false,
    textures: { top: 6, bottom: 6, sides: 6 },
    emissive: false,
  },
  {
    id: BlockId.WOOD,
    name: 'Wood',
    transparent: false,
    solid: true,
    textures: { top: 8, bottom: 8, sides: 7 },
    emissive: false,
  },
  {
    id: BlockId.LEAVES,
    name: 'Leaves',
    transparent: true,
    solid: true,
    textures: { top: 9, bottom: 9, sides: 9 },
    emissive: false,
  },
  {
    id: BlockId.SNOW,
    name: 'Snow',
    transparent: false,
    solid: true,
    textures: { top: 10, bottom: 3, sides: 11 },
    emissive: false,
  },
  {
    id: BlockId.GRAVEL,
    name: 'Gravel',
    transparent: false,
    solid: true,
    textures: { top: 12, bottom: 12, sides: 12 },
    emissive: false,
  },
  {
    id: BlockId.COAL_ORE,
    name: 'Coal Ore',
    transparent: false,
    solid: true,
    textures: { top: 13, bottom: 13, sides: 13 },
    emissive: false,
  },
  {
    id: BlockId.IRON_ORE,
    name: 'Iron Ore',
    transparent: false,
    solid: true,
    textures: { top: 14, bottom: 14, sides: 14 },
    emissive: false,
  },
  {
    id: BlockId.GOLD_ORE,
    name: 'Gold Ore',
    transparent: false,
    solid: true,
    textures: { top: 15, bottom: 15, sides: 15 },
    emissive: false,
  },
  {
    id: BlockId.DIAMOND_ORE,
    name: 'Diamond Ore',
    transparent: false,
    solid: true,
    textures: { top: 16, bottom: 16, sides: 16 },
    emissive: true,
  },
  {
    id: BlockId.OBSIDIAN,
    name: 'Obsidian',
    transparent: false,
    solid: true,
    textures: { top: 17, bottom: 17, sides: 17 },
    emissive: false,
  },
  {
    id: BlockId.LAVA,
    name: 'Lava',
    transparent: true,
    solid: false,
    textures: { top: 18, bottom: 18, sides: 18 },
    emissive: true,
  },
  {
    id: BlockId.CRYSTAL,
    name: 'Crystal',
    transparent: true,
    solid: true,
    textures: { top: 19, bottom: 19, sides: 19 },
    emissive: true,
  },
  {
    id: BlockId.CACTUS,
    name: 'Cactus',
    transparent: false,
    solid: true,
    textures: { top: 21, bottom: 21, sides: 20 },
    emissive: false,
  },
  {
    id: BlockId.MUSHROOM,
    name: 'Mushroom',
    transparent: true,
    solid: false,
    textures: { top: 22, bottom: 22, sides: 22 },
    emissive: true,
  },
  {
    id: BlockId.PLANKS,
    name: 'Planks',
    transparent: false,
    solid: true,
    textures: { top: 23, bottom: 23, sides: 23 },
    emissive: false,
  },
] as const;
